import { navigationAr } from './navigation/ar';
import { navigationEn } from './navigation/en';
import { faqAr } from './faq/ar';
import { faqEn } from './faq/en';
import { homeAr } from './site/ar/home';
import { homeEn } from './site/en/home';
import { servicesAr } from './services/ar';
import { servicesEn } from './services/en';
import { workAr } from './work/ar';
import { workEn } from './work/en';
import { insightsAr } from './insights/ar';
import { insightsEn } from './insights/en';
import { aboutAr } from './site/ar/about';
import { aboutEn } from './site/en/about';
import { processAr } from './site/ar/process';
import { processEn } from './site/en/process';
import { contactAr } from './site/ar/contact';
import { contactEn } from './site/en/contact';
import { startProjectAr } from './site/ar/start-project';
import { startProjectEn } from './site/en/start-project';
import type { Locale } from '@/lib/i18n/config';

export const getNavigation = (locale: Locale) => (locale === 'ar' ? navigationAr : navigationEn);
export const getHomeContent = (locale: Locale) => (locale === 'ar' ? homeAr : homeEn);
export const getServices = (locale: Locale) => (locale === 'ar' ? servicesAr : servicesEn);
export const getWork = (locale: Locale) => (locale === 'ar' ? workAr : workEn);
export const getInsights = (locale: Locale) => (locale === 'ar' ? insightsAr : insightsEn);
export const getFaq = (locale: Locale) => (locale === 'ar' ? faqAr : faqEn);
export const getAbout = (locale: Locale) => (locale === 'ar' ? aboutAr : aboutEn);
export const getProcess = (locale: Locale) => (locale === 'ar' ? processAr : processEn);
export const getContact = (locale: Locale) => (locale === 'ar' ? contactAr : contactEn);
export const getStartProject = (locale: Locale) => (locale === 'ar' ? startProjectAr : startProjectEn);
